### ISSUE TITLE
Extinction style pools - burning hMOCHI

### ISSUE THREAD

**Issue by crypto-gainz** [mochiswap/harmony-farms-frontend#2]
We should add Extinction style pools (a la Dinoswap) to help new projects with their token emissions.

It would also help us burn hMOCHI since the entrance fee in the pools would be paid in hMOCHIs.

We can make a Google Sheets doc that we post on the Webste + Docs and people can fill it in with the required information: how many tokens they want to send to Mochiswap for that pool, until when should it last, what should de emissions be, etc.

**Comment by hashparty1** [comment]
Closing as this has been started and has its own repo now
